---
micronaut:
  application:
    name: routing-app
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:public
---
micronaut:
  io:
    watch:
      paths: src/main
      restart: true